# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  solution: 'Project2-TCG/Project2-TCG.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

stages:
- stage: Install
  jobs:
    
    -job: NugetInstall
    steps:
    - task: NuGetToolInstaller@1
      inputs:
        versionSpec: 
    - task: NuGetCommand@2
      inputs:
        command: 'restore'
        restoreSolution: 'Project2-TCG/Project2-TCG.sln'
        feedsToUse: 'select'

- stage: Sonar_API
  jobs:
    
    -job: Scan
    steps:
      - task: SonarCloudPrepare@1
        inputs:
          organization: '210726-wvu-net-ext 210726-wvu-net-ext'
          scannerMode: 'MSBuild'
          projectKey: 'n-Ea210726-wvu-net-ext_P2-Group-1--Ryarles--Liam-Sloan--Sean-Fitzmaurice'
          projectName: 'P2-Group-1--Ryan-Earles--Liam-Sloan--Sean-Fitzmaurice'
      - task: DotNetCoreCLI@2
        inputs:
          command: 'build'
      - task: DotNetCoreCLI@2
        inputs:
          command: 'test'
      - task: SonarCloudAnalyze@1
      - task: SonarCloudPublish@1
        inputs:
          pollingTimeoutSec: '300'


